### ISSUE TITLE
I have some questions about the laplace mechanism

### ISSUE THREAD

**Issue by DDDIII123** [Quantalabs/DiffPriv#3]
In function lapmech
` if delta_f is None:

        delta_f = []
        data_draft = []

        for c in range(columns):

            data_draft.append([float(raw_data[r].split(',')[c]) for r in range(rows)])
            samples = [int(rows * rd.random()) for i in range(sample_size)]
            delta_f.append(0.01)

            for i in samples:

                x_prime = [x for x in data_draft[-1]]
                x_prime[i] += 1
                delta_f[-1] = max(delta_f[-1], abs(f(data_draft[-1])-f(x_prime)))

Why  x_prime[i] only adds 1? 
And is the definition of the neighbor dataset like this?

**Comment by quantum9Innovation** [comment]
Yes. 

The Laplace Mechanism differentially-privatizes datasets depending on a specific query. In this case, the query is the function `f`, given as a parameter to the `lapmech` function. If the query produces more or less the same results even when the dataset is changed to a "neighbor dataset," then the data doesn't need to be changed much since an attacker won't be able to find the real data by seeing the query, since the query is extremely general (i.e. it doesn't change much based on the data). However, if the query was instead extremely sensitive to small changes in the data, the attacker would easily be able to recover the original data even after the query was performed. In this case, the dataset needs to be changed significantly.

In order to deal with this, the Laplace Mechanism defines a "neighbor dataset" as a dataset where one value in each row, or in this case column, of the dataset is changed by 1 unit. Then, a measure of the "sensitivity" of a certain query `f` is defined as the maximum change in `f` given a change of one unit to any value within that portion of the dataset.

In theory, the idea would be to go through every single dataset value and change it by one to check the sensitivity of `f` on that specific value and then record the maximum sensitivity. Unfortunately, this strategy would be inefficient and computationally expensive. Instead, the DiffPriv library draws random samples from the dataset to check for maximum sensitivity. This achieves a very good estimate of the sensitivity of `f` while allowing the script to execute in very little time.

**Comment by quantum9Innovation** [comment]
[This pdf](https://www.seas.upenn.edu/~cis399/files/lecture/l21.pdf) has more of the details, and the sensitivity details are discussed in the first paragraph.

**Comment by quantum9Innovation** [comment]
> Yes.
> 
> The Laplace Mechanism differentially-privatizes datasets depending on a specific query. In this case, the query is the function `f`, given as a parameter to the `lapmech` function. If the query produces more or less the same results even when the dataset is changed to a "neighbor dataset," then the data doesn't need to be changed much since an attacker won't be able to find the real data by seeing the query, since the query is extremely general (i.e. it doesn't change much based on the data). However, if the query was instead extremely sensitive to small changes in the data, the attacker would easily be able to recover the original data even after the query was performed. In this case, the dataset needs to be changed significantly.
> 
> In order to deal with this, the Laplace Mechanism defines a "neighbor dataset" as a dataset where one value in each row, or in this case column, of the dataset is changed by 1 unit. Then, a measure of the "sensitivity" of a certain query `f` is defined as the maximum change in `f` given a change of one unit to any value within that portion of the dataset.
> 
> In theory, the idea would be to go through every single dataset value and change it by one to check the sensitivity of `f` on that specific value and then record the maximum sensitivity. Unfortunately, this strategy would be inefficient and computationally expensive. Instead, the DiffPriv library draws random samples from the dataset to check for maximum sensitivity. This achieves a very good estimate of the sensitivity of `f` while allowing the script to execute in very little time.

Just as a side note, the number of samples to draw from the dataset is set by default to around 10, but you can easily change that number for more accurate sensitivity predictions.

**Comment by DDDIII123** [comment]
Thank you for your answer.
